### ISSUE TITLE
Motor faders

### ISSUE THREAD

**Issue by fab34555426** [paradajz/OpenDeck#13]
Is it possible to connect motorfaders? I want to use this for my DIY DAW-Controller

**Comment by paradajz** [comment]
That's not possible currently - I am planning on supporting it but it's not really high on the priority list at the moment.

**Comment by alexandreleroux** [comment]
@paradajz , are classic non-motorized faders supported? I'm new to OpenDeck and I found no reference to faders at all in the documentation. Thanks!

**Comment by paradajz** [comment]
Yes, of course. I've mentioned potentiometers but faders are technically the same thing.
