### ISSUE TITLE
Multiplexers

### ISSUE THREAD

**Issue by gbrandt1** [paradajz/OpenDeck#17]
Hi,
Very cool project, thanks for sharing as open source!
My main question at this point:

Do you plan to support multiplexers in the future?

Cheers

**Comment by paradajz** [comment]
Thanks!

I'm not sure what do you mean. Official OpenDeck board already uses multiplexers. There's also buildable target for Arduino Mega with 6 multiplexers.

**Comment by gbrandt1** [comment]
yes sorry i meant for third-party MCU. cool thanks i didn't see the Arduino Mega 6mux target! (i was only reading the wiki so far)

**Comment by paradajz** [comment]
All right. I'll close this then. Let me know if you'll need some more info.
