### ISSUE TITLE
Teensy 3.6 support

### ISSUE THREAD

**Issue by uroborov** [paradajz/OpenDeck#18]
Hi, I'm building a MIDI controller based on teensy 3.6. Using Opendeck would make my work easier. however, it seems that only teensy 2.0 is supported. are there any plans or workaround to make it work on teensy 3.6?

**Comment by paradajz** [comment]
Hi,

it's not planned at the moment. I am planning on supporting various STM32 development boards later this year, but not Teensy 3+ for now, unfortunately.
