### ISSUE TITLE
Arduino Mega 2560 REV3 only has 1 header

### ISSUE THREAD

**Issue by adiastra** [paradajz/OpenDeck#20]
So I flashed the Mega 2560 using an Uno as ISP and it worked, but the configurator does not recognize the board is connected. The 2560 R3 only has one header. Does something else need to be done for the rev3 with single header to work properly? (this uses the ch340  usb chip)

**Comment by paradajz** [comment]
Mega with ch340 can't work with OpenDeck firmware. You need Mega with ATmega16u2 MCU used for USB communication because you need to reprogram it with USB MIDI OpenDeck firmware.

**Comment by adiastra** [comment]
Thanks, I have a few on the way.
