### ISSUE TITLE
Error when trying to flash pre-built binary (Pro Micro)

### ISSUE THREAD

**Issue by mungewell** [paradajz/OpenDeck#29]
I have clone the repo, but I wish to flash pre-built rather than build myself. I think i am running the right commands but I get the following error
```
$ sudo ./scripts/flash.sh 
[sudo] password for simon: 
Please select serial port on which ArduinoISP is connected:
     1	ttyACM0
1
Please select board you want to flash and then press enter:
     1	arrival
     2	bergamot
     3	dubfocus
     4	jamiel
     5	mega16u2
     6	mega2560
     7	mega2560_6mux
     8	mega2560_jose
     9	opendeck
    10	teensy2pp
    11	uno
    12	uno16u2
Board number: 5
Please wait...
cat: ./build/DEBUG: No such file or directory
cat: ./build/BOOT: No such file or directory
Makefile:13: *** Target doesn't exist.  Stop.
```

**Comment by mungewell** [comment]
I was able to flash the Pro Micro by back-tracking to
`commit 96dd93f738a39cb64ebbfec7e945be38df7e0e41 (HEAD, tag: v4.0.0)`

**Comment by paradajz** [comment]
Fixed with https://github.com/paradajz/OpenDeck/commit/e82723886736cae89cf3cb7cad3b3bfd463947ac

Can you try again?

**Comment by mungewell** [comment]
Late last night I realized that you had removed support for the ProMicro (not related to this bug BTW), with
```
commit cccddc142dd0c43b2dbc78ccbaea08ef20b411dc
Author: paradajz <2544094+paradajz@users.noreply.github.com>
Date:   Sun Apr 19 10:00:22 2020 +0200

    drop support for bootloader on arduino leonardo/promicro
    
    it won't fit anymore together with flash
```

If I grabbed the 'ProMicro.hex' from the previous rev and then used that together with HEAD I was able to flash the board with the fixed script.
```
git checkout 6c486272491c311df9cfefcfc67ed4d741951d4d
cp bin/compiled/merged/avr/atmega32u4/promicro.hex .
git checkout master
cp promicro.hex bin/compiled/merged/avr/atmega32u4/promicro.hex
sudo scripts/flash.sh
```

So, I consider this a success/fix, thanks.
![promicro_most_recent_build](https://user-images.githubusercontent.com/236907/82474059-b7045b80-9a87-11ea-8eda-5aa92be6f00d.png)

**Comment by paradajz** [comment]
It's not the ProMicro support that was removed - support for bootloader on ProMicro and Leonardo was removed. Glad it works though, and I'll also correct the naming in the UI.
