### ISSUE TITLE
Web browser is unable to find (Arduino based) OpenDeck

### ISSUE THREAD

**Issue by mungewell** [paradajz/OpenDeck#8]
Hi awesome project, managed to build and flash an Arduino ProMicro by following the instructions on the wiki.

Unfortunately the WebConfigurator does not find the board, is there something special I need to do? Mozilla Firefox on Ubuntu Linux.

The board is seen via the command line, using the SysEx commands
```
$ amidi -p hw:1,0,0 -S 'F0 00 53 43 00 00 01 F7' -r resp.bin
^C
7 bytes read
$ hexdump -Cv resp.bin 
00000000  f0 00 53 43 01 00 f7                              |..SC...|
00000007
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0cf3:e301 Atheros Communications, Inc. 
Bus 001 Device 003: ID 187c:0527 Alienware Corporation 
Bus 001 Device 002: ID 0c45:6708 Microdia 
Bus 001 Device 014: ID 1209:8472 InterBiometrics 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by paradajz** [comment]
Firefox does not support WebMIDI - only Chrome/Chromium and Opera currently support the spec.
